export const METRIC_GROUPS = [
  {
    id: 'population',
    label: 'Population & Scale',
    blurb: 'ZIP size, density, and overall household volume.',
  },
  {
    id: 'age',
    label: 'Age Profile',
    blurb: 'Age mix and household life-stage signals.',
  },
  {
    id: 'race',
    label: 'Race & Ethnicity',
    blurb: 'Audience composition shares based on current population.',
  },
  {
    id: 'income',
    label: 'Income & Education',
    blurb: 'Spending power, education depth, and affluent household mix.',
  },
  {
    id: 'housing',
    label: 'Housing & Workforce',
    blurb: 'Tenure, home value, employment, and job mix.',
  },
];

export const METRICS = [
  {
    id: 'pop',
    key: 'pop',
    group: 'population',
    label: 'Total Population',
    shortLabel: 'Population',
    description: 'Current ZIP-level population count.',
    format: 'integer',
    inputStep: 100,
    comparatorStep: 100,
    scaleMode: 'log',
  },
  {
    id: 'hh',
    key: 'hh',
    group: 'population',
    label: 'Households',
    shortLabel: 'Households',
    description: 'Current ZIP-level household count.',
    format: 'integer',
    inputStep: 50,
    comparatorStep: 50,
    scaleMode: 'log',
  },
  {
    id: 'dens',
    key: 'dens',
    group: 'population',
    label: 'Population Density',
    shortLabel: 'Density',
    description: 'Population per square mile.',
    format: 'decimal',
    decimals: 1,
    inputStep: 10,
    comparatorStep: 10,
    scaleMode: 'log',
  },
  {
    id: 'ma',
    key: 'ma',
    group: 'age',
    label: 'Median Age',
    shortLabel: 'Median age',
    description: 'Median age of the ZIP population.',
    format: 'decimal',
    decimals: 1,
    inputStep: 0.5,
    comparatorStep: 1,
    scaleMode: 'linear',
  },
  {
    id: 'child',
    key: 'child',
    group: 'age',
    label: 'Children Share (0-17)',
    shortLabel: 'Children 0-17',
    description: 'Share of residents ages 0 through 17.',
    format: 'percent',
    inputStep: 0.5,
    comparatorStep: 1,
    scaleMode: 'linear',
  },
  {
    id: 'young',
    key: 'young',
    group: 'age',
    label: 'Young Adults Share (18-34)',
    shortLabel: 'Young adults 18-34',
    description: 'Share of residents ages 18 through 34.',
    format: 'percent',
    inputStep: 0.5,
    comparatorStep: 1,
    scaleMode: 'linear',
  },
  {
    id: 'mid',
    key: 'mid',
    group: 'age',
    label: 'Midlife Share (35-54)',
    shortLabel: 'Midlife 35-54',
    description: 'Share of residents ages 35 through 54.',
    format: 'percent',
    inputStep: 0.5,
    comparatorStep: 1,
    scaleMode: 'linear',
  },
  {
    id: 'age55',
    key: 'age55',
    group: 'age',
    label: 'Older Adults Share (55+)',
    shortLabel: 'Adults 55+',
    description: 'Share of residents ages 55 and above.',
    format: 'percent',
    inputStep: 0.5,
    comparatorStep: 1,
    scaleMode: 'linear',
  },
  {
    id: 'sen',
    key: 'sen',
    group: 'age',
    label: 'Seniors Share (65+)',
    shortLabel: 'Seniors 65+',
    description: 'Share of residents ages 65 and above.',
    format: 'percent',
    inputStep: 0.5,
    comparatorStep: 1,
    scaleMode: 'linear',
  },
  {
    id: 'his',
    key: 'his',
    group: 'race',
    label: 'Hispanic / Latino Share',
    shortLabel: 'Hispanic share',
    description: 'Share of residents identifying as Hispanic or Latino.',
    format: 'percent',
    inputStep: 0.5,
    comparatorStep: 1,
    scaleMode: 'linear',
  },
  {
    id: 'wht',
    key: 'wht',
    group: 'race',
    label: 'White Alone Share',
    shortLabel: 'White share',
    description: 'Share of residents identifying as White alone.',
    format: 'percent',
    inputStep: 0.5,
    comparatorStep: 1,
    scaleMode: 'linear',
  },
  {
    id: 'blk',
    key: 'blk',
    group: 'race',
    label: 'Black Share',
    shortLabel: 'Black share',
    description: 'Share of residents identifying as Black or African American alone.',
    format: 'percent',
    inputStep: 0.5,
    comparatorStep: 1,
    scaleMode: 'linear',
  },
  {
    id: 'asn',
    key: 'asn',
    group: 'race',
    label: 'Asian Share',
    shortLabel: 'Asian share',
    description: 'Share of residents identifying as Asian alone.',
    format: 'percent',
    inputStep: 0.5,
    comparatorStep: 1,
    scaleMode: 'linear',
  },
  {
    id: 'mhi',
    key: 'mhi',
    group: 'income',
    label: 'Median Household Income',
    shortLabel: 'Median income',
    description: 'Median household income for the ZIP.',
    format: 'currency',
    inputStep: 1000,
    comparatorStep: 5000,
    scaleMode: 'log',
  },
  {
    id: 'col',
    key: 'col',
    group: 'income',
    label: 'College+ Share',
    shortLabel: 'College+',
    description: 'Share of population 25+ with a bachelor’s degree or higher.',
    format: 'percent',
    inputStep: 0.5,
    comparatorStep: 1,
    scaleMode: 'linear',
  },
  {
    id: 'adv',
    key: 'adv',
    group: 'income',
    label: 'Advanced Degree Share',
    shortLabel: 'Advanced degrees',
    description: 'Share of population 25+ with a master’s, professional, or doctorate degree.',
    format: 'percent',
    inputStep: 0.5,
    comparatorStep: 1,
    scaleMode: 'linear',
  },
  {
    id: 'hiinc',
    key: 'hiinc',
    group: 'income',
    label: 'High-Income Household Share ($150k+)',
    shortLabel: 'HH income $150k+',
    description: 'Share of households earning $150,000 or more.',
    format: 'percent',
    inputStep: 0.5,
    comparatorStep: 1,
    scaleMode: 'linear',
  },
  {
    id: 'lowinc',
    key: 'lowinc',
    group: 'income',
    label: 'Lower-Income Household Share (<$50k)',
    shortLabel: 'HH income <$50k',
    description: 'Share of households earning under $50,000.',
    format: 'percent',
    inputStep: 0.5,
    comparatorStep: 1,
    scaleMode: 'linear',
  },
  {
    id: 'own',
    key: 'own',
    group: 'housing',
    label: 'Owner-Occupied Share',
    shortLabel: 'Owner occupied',
    description: 'Share of occupied housing units that are owner-occupied.',
    format: 'percent',
    inputStep: 0.5,
    comparatorStep: 1,
    scaleMode: 'linear',
  },
  {
    id: 'rent',
    key: 'rent',
    group: 'housing',
    label: 'Renter Share',
    shortLabel: 'Renter occupied',
    description: 'Share of occupied housing units that are renter-occupied.',
    format: 'percent',
    inputStep: 0.5,
    comparatorStep: 1,
    scaleMode: 'linear',
  },
  {
    id: 'mhv',
    key: 'mhv',
    group: 'housing',
    label: 'Median Home Value',
    shortLabel: 'Median home value',
    description: 'Median value of owner-occupied housing units.',
    format: 'currency',
    inputStep: 5000,
    comparatorStep: 10000,
    scaleMode: 'log',
  },
  {
    id: 'unemp',
    key: 'unemp',
    group: 'housing',
    label: 'Unemployment Rate',
    shortLabel: 'Unemployment',
    description: 'Share of the civilian labor force currently unemployed.',
    format: 'percent',
    inputStep: 0.25,
    comparatorStep: 0.5,
    scaleMode: 'linear',
  },
  {
    id: 'wc',
    key: 'wc',
    group: 'housing',
    label: 'White-Collar Worker Share',
    shortLabel: 'White-collar workers',
    description: 'Share of employed workers in white-collar occupations.',
    format: 'percent',
    inputStep: 0.5,
    comparatorStep: 1,
    scaleMode: 'linear',
  },
  {
    id: 'povfam',
    key: 'povfam',
    group: 'housing',
    label: 'Families Below Poverty Share',
    shortLabel: 'Families below poverty',
    description: 'Share of families living below the poverty line.',
    format: 'percent',
    inputStep: 0.5,
    comparatorStep: 1,
    scaleMode: 'linear',
  },
];

export const METRICS_BY_ID = Object.fromEntries(METRICS.map((metric) => [metric.id, metric]));
export const GROUPS_BY_ID = Object.fromEntries(METRIC_GROUPS.map((group) => [group.id, group]));

export const POPULAR_CUTS = [
  {
    label: 'Median income $100k+',
    group: 'income',
    metricId: 'mhi',
    comparator: 'gte',
    value1: 100000,
  },
  {
    label: 'College+ 40%+',
    group: 'income',
    metricId: 'col',
    comparator: 'gte',
    value1: 40,
  },
  {
    label: 'HH income $150k+ share 20%+',
    group: 'income',
    metricId: 'hiinc',
    comparator: 'gte',
    value1: 20,
  },
  {
    label: 'Hispanic share 30%+',
    group: 'race',
    metricId: 'his',
    comparator: 'gte',
    value1: 30,
  },
  {
    label: 'Black share 20%+',
    group: 'race',
    metricId: 'blk',
    comparator: 'gte',
    value1: 20,
  },
  {
    label: 'Asian share 15%+',
    group: 'race',
    metricId: 'asn',
    comparator: 'gte',
    value1: 15,
  },
  {
    label: 'Young adults 25%+',
    group: 'age',
    metricId: 'young',
    comparator: 'gte',
    value1: 25,
  },
  {
    label: 'Seniors 20%+',
    group: 'age',
    metricId: 'sen',
    comparator: 'gte',
    value1: 20,
  },
  {
    label: 'Owner occupied 60%+',
    group: 'housing',
    metricId: 'own',
    comparator: 'gte',
    value1: 60,
  },
  {
    label: 'White-collar 45%+',
    group: 'housing',
    metricId: 'wc',
    comparator: 'gte',
    value1: 45,
  },
  {
    label: 'Unemployment 5% or lower',
    group: 'housing',
    metricId: 'unemp',
    comparator: 'lte',
    value1: 5,
  },
  {
    label: 'Dense ZIPs 2k+/sq mi',
    group: 'population',
    metricId: 'dens',
    comparator: 'gte',
    value1: 2000,
  },
];

export const COMPARATORS = [
  {
    value: 'gte',
    label: 'is at least',
  },
  {
    value: 'lte',
    label: 'is at most',
  },
  {
    value: 'between',
    label: 'is between',
  },
];

export const DEFAULT_STATE = {
  selectedMetricId: 'mhi',
  state: '',
  county: '',
  msa: '',
  search: '',
  minPopulation: '',
  excludeZero: true,
  cuts: [],
};

export const HEAT_GRADIENT = {
  0.05: '#f8d88c',
  0.35: '#f39c3f',
  0.6: '#e86a33',
  0.85: '#c7422d',
  1.0: '#741e24',
};
